server:
  port: 8080

logging:
  level:
    org.springframework.security: TRACE

spring:
  application:
    name: Single-Sign-On
  #profiles:
  # active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?useSSL=false&serverTimezone=UTC
    username: root
    password: 2005
  data:
    redis:
      password:
      port: 6379
      host: 127.0.0.1
  devtools:
    restart:
      enabled: true

